// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgR9CEafNWJ97xPOgX3_JdOg-DK0QEWag',
    appId: '1:393723016928:web:e7172e38d7bab5a0a40285',
    messagingSenderId: '393723016928',
    projectId: 'flashcard-fa846',
    authDomain: 'flashcard-fa846.firebaseapp.com',
    storageBucket: 'flashcard-fa846.firebasestorage.app',
    measurementId: 'G-2H7FQHJZRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASEtXhYXAO2AqLHfc-c1vrW774H4fqQvk',
    appId: '1:393723016928:android:40c576f4b8c1c351a40285',
    messagingSenderId: '393723016928',
    projectId: 'flashcard-fa846',
    storageBucket: 'flashcard-fa846.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgR9CEafNWJ97xPOgX3_JdOg-DK0QEWag',
    appId: '1:393723016928:web:cdf5c0c02616ab81a40285',
    messagingSenderId: '393723016928',
    projectId: 'flashcard-fa846',
    authDomain: 'flashcard-fa846.firebaseapp.com',
    storageBucket: 'flashcard-fa846.firebasestorage.app',
    measurementId: 'G-1FXQXWNYXB',
  );
}
